require_relative '../../app/helpers/connection_helper'

include ConnectionHelper

desc 'Ingest recipes from file'
task :ingest_recipes => :environment do
  require 'pg'
  begin
    file = Dir.pwd + '/recipes.json'
    conn.exec(sql_string(file))
  ensure
    conn.close
  end
end

private

def sql_string(file)
  <<~HEREDOC.strip
    BEGIN;
      CREATE TABLE recipes (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        data jsonb NOT NULL
        );
      CREATE INDEX on recipes using gin ((data->'ingredients'));
      COPY recipes (data) FROM '#{file}';
    COMMIT;
  HEREDOC
end
